<?php
return [
  '_SERVER' => [
    'HTTP_HOST' => 'localhost',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:34.0) Gecko/20100101 Firefox/34.0',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'HTTP_ACCEPT_LANGUAGE' => 'gl-gl,gl;q=0.8,es;q=0.6,en-us;q=0.4,en;q=0.2',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
    'HTTP_DNT' => '1',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_CACHE_CONTROL' => 'max-age=0',
    'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin',
    'SERVER_SIGNATURE' => '',
    'SERVER_SOFTWARE' => 'Apache/2.4.9 (Unix)',
    'SERVER_NAME' => 'localhost',
    'SERVER_ADDR' => '::1',
    'SERVER_PORT' => '80',
    'REMOTE_ADDR' => '::1',
    'DOCUMENT_ROOT' => '/Users/oscarotero/www',
    'REQUEST_SCHEME' => 'http',
    'CONTEXT_PREFIX' => '',
    'CONTEXT_DOCUMENT_ROOT' => '/Users/oscarotero/www',
    'SERVER_ADMIN' => 'you@example.com',
    'SCRIPT_FILENAME' => '/Users/oscarotero/www/test.php',
    'REMOTE_PORT' => '64726',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'REQUEST_METHOD' => 'POST',
    'QUERY_STRING' => '',
    'REQUEST_URI' => '/test.php',
    'SCRIPT_NAME' => '/test.php',
    'PHP_SELF' => '/test.php',
    'REQUEST_TIME_FLOAT' => 1421091519.099,
    'REQUEST_TIME' => 1421091519,
  ],
  '_GET' => [],
  '_POST' => [],
  '_FILES' => [],
  '_COOKIE' => [],
  'input' => __DIR__.'/input.txt',
];
